name: docs

on:
  push:
    branches:
      - "foxy"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Build and push docs
        uses: athackst/mkdocs-simple-plugin@v3.1.0
